/**
 * Mock email data for development mode.
 * Used when __DEV__ is true to populate the inbox with realistic test data.
 */

import type { Message, Mailbox } from '@/services/emailApi';

const now = new Date();
const hours = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const days = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_MAILBOXES: Mailbox[] = [
  { _id: 'mb-inbox', name: 'Inbox', path: 'INBOX', specialUse: 'Inbox', totalMessages: 18, unseenMessages: 6 },
  { _id: 'mb-sent', name: 'Sent', path: 'Sent', specialUse: 'Sent', totalMessages: 42, unseenMessages: 0 },
  { _id: 'mb-drafts', name: 'Drafts', path: 'Drafts', specialUse: 'Drafts', totalMessages: 3, unseenMessages: 0 },
  { _id: 'mb-archive', name: 'Archive', path: 'Archive', specialUse: 'Archive', totalMessages: 156, unseenMessages: 0 },
  { _id: 'mb-trash', name: 'Trash', path: 'Trash', specialUse: 'Trash', totalMessages: 8, unseenMessages: 0 },
  { _id: 'mb-spam', name: 'Spam', path: 'Spam', specialUse: 'Junk', totalMessages: 12, unseenMessages: 12 },
];

export const MOCK_MESSAGES: Message[] = [
  {
    _id: 'msg-1',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg1@example.com>',
    from: { name: 'Sarah Chen', address: 'sarah.chen@designstudio.co' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Updated mockups for the dashboard redesign',
    text: 'Hey! I just finished the latest iteration of the dashboard mockups. The new layout addresses the feedback from last week\'s review — simplified navigation, better data density, and the updated color palette. Let me know your thoughts before I hand off to engineering.',
    html: '',
    attachments: [
      { filename: 'Dashboard-v3.fig', contentType: 'application/octet-stream', size: 2400000, s3Key: 'att-1' },
      { filename: 'preview-screenshot.png', contentType: 'image/png', size: 850000, s3Key: 'att-2' },
      { filename: 'component-specs.pdf', contentType: 'application/pdf', size: 1200000, s3Key: 'att-3' },
    ],
    flags: { seen: false, starred: true, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 4500000,
    date: hours(1),
    receivedAt: hours(1),
  },
  {
    _id: 'msg-2',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg2@example.com>',
    from: { name: 'GitHub', address: 'noreply@github.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: '[OxyHQ/services] Pull request #174: Fix auth token refresh race condition',
    text: 'Marcus Rivera opened a pull request in OxyHQ/services. This PR fixes the race condition that occurs when multiple API calls trigger a token refresh simultaneously. Added a mutex lock around the refresh logic and a request queue to batch pending calls.',
    html: '',
    attachments: [],
    flags: { seen: false, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 12000,
    date: hours(2),
    receivedAt: hours(2),
  },
  {
    _id: 'msg-3',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg3@example.com>',
    from: { name: 'Alex Thompson', address: 'alex@startup.io' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    cc: [{ name: 'Engineering Team', address: 'eng@startup.io' }],
    subject: 'Q1 Planning: Engineering priorities and roadmap',
    text: 'Team, I\'ve put together the Q1 roadmap based on our strategy session. Key priorities: 1) Ship the mobile app v2.0, 2) Migrate to the new auth system, 3) Performance improvements on the dashboard. Please review the attached spreadsheet and add your estimates by Friday.',
    html: '',
    attachments: [
      { filename: 'Q1-Roadmap-2026.xlsx', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', size: 45000, s3Key: 'att-4' },
    ],
    flags: { seen: false, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 57000,
    date: hours(3),
    receivedAt: hours(3),
  },
  {
    _id: 'msg-4',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg4@example.com>',
    from: { name: 'Stripe', address: 'receipts@stripe.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Your receipt from Vercel Inc.',
    text: 'Payment receipt for $20.00 USD. Vercel Pro Plan — Monthly subscription. Card ending in 4242. Thank you for your payment.',
    html: '',
    attachments: [
      { filename: 'receipt-2026-01.pdf', contentType: 'application/pdf', size: 32000, s3Key: 'att-5' },
    ],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 44000,
    date: hours(5),
    receivedAt: hours(5),
  },
  {
    _id: 'msg-5',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg5@example.com>',
    from: { name: 'Emma Rodriguez', address: 'emma.r@company.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Re: Coffee chat next week?',
    text: 'Sounds great! How about Tuesday at 2pm? There\'s a new place on 5th that I\'ve been wanting to try. They have amazing pour-over coffee.',
    html: '',
    attachments: [],
    flags: { seen: true, starred: false, answered: true, forwarded: false, draft: false },
    labels: [],
    size: 5000,
    inReplyTo: '<msg-prev@example.com>',
    date: hours(6),
    receivedAt: hours(6),
  },
  {
    _id: 'msg-6',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg6@example.com>',
    from: { name: 'Linear', address: 'notifications@linear.app' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'INB-342: Email compose screen - add attachment support',
    text: 'James Park moved INB-342 to In Progress. Priority: High. Assignee: You. Add the ability to attach files when composing emails. Support drag-and-drop on web and file picker on mobile.',
    html: '',
    attachments: [],
    flags: { seen: false, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 8000,
    date: hours(8),
    receivedAt: hours(8),
  },
  {
    _id: 'msg-7',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg7@example.com>',
    from: { name: 'David Kim', address: 'david.kim@agency.design' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Brand assets and style guide delivery',
    text: 'Hi! As promised, here are the finalized brand assets. The package includes the logo in all formats, the complete icon set, typography guidelines, and the full color palette. The style guide PDF has everything documented.',
    html: '',
    attachments: [
      { filename: 'brand-assets.zip', contentType: 'application/zip', size: 15600000, s3Key: 'att-6' },
      { filename: 'style-guide.pdf', contentType: 'application/pdf', size: 3200000, s3Key: 'att-7' },
      { filename: 'logo-dark.svg', contentType: 'image/svg+xml', size: 8500, s3Key: 'att-8' },
      { filename: 'logo-light.svg', contentType: 'image/svg+xml', size: 8200, s3Key: 'att-9' },
      { filename: 'icon-set.zip', contentType: 'application/zip', size: 4500000, s3Key: 'att-10' },
    ],
    flags: { seen: true, starred: true, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 23400000,
    date: days(1),
    receivedAt: days(1),
  },
  {
    _id: 'msg-8',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg8@example.com>',
    from: { name: 'Google Cloud', address: 'cloud-noreply@google.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Your January billing summary',
    text: 'Your Google Cloud billing summary for January 2026. Total charges: $127.43. Compute Engine: $89.20, Cloud Storage: $23.15, Cloud Functions: $15.08. Your next payment will be processed on February 5, 2026.',
    html: '',
    attachments: [],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 15000,
    date: days(1),
    receivedAt: days(1),
  },
  {
    _id: 'msg-9',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg9@example.com>',
    from: { name: 'Olivia Martinez', address: 'olivia@team.dev' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Sprint retro notes and action items',
    text: 'Here are the notes from today\'s retro. Main takeaways: deployment pipeline needs better error logging, we should set up staging environment alerts, and the onboarding docs are outdated. I\'ve assigned action items in the doc.',
    html: '',
    attachments: [
      { filename: 'retro-notes-sprint-14.docx', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: 28000, s3Key: 'att-11' },
    ],
    flags: { seen: false, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 40000,
    date: days(2),
    receivedAt: days(2),
  },
  {
    _id: 'msg-10',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg10@example.com>',
    from: { name: 'Notion', address: 'notify@mail.notion.so' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'James Park mentioned you in "API Documentation"',
    text: '@you Can you review the auth section? I want to make sure the token refresh flow is documented correctly before we publish.',
    html: '',
    attachments: [],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 6000,
    date: days(2),
    receivedAt: days(2),
  },
  {
    _id: 'msg-11',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg11@example.com>',
    from: { name: 'Ryan Foster', address: 'ryan@freelance.me' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Invoice #1047 — January consulting',
    text: 'Hi, please find attached my invoice for the consulting work in January. Total: $4,500.00. Breakdown: 30 hours @ $150/hr. Payment terms: Net 15. Let me know if you have any questions.',
    html: '',
    attachments: [
      { filename: 'invoice-1047.pdf', contentType: 'application/pdf', size: 95000, s3Key: 'att-12' },
    ],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 107000,
    date: days(3),
    receivedAt: days(3),
  },
  {
    _id: 'msg-12',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg12@example.com>',
    from: { name: 'AWS', address: 'no-reply@sns.amazonaws.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'ALARM: "API-Latency-High" in US-East-1',
    text: 'You are receiving this email because your Amazon CloudWatch Alarm "API-Latency-High" in the US East (N. Virginia) region has entered the ALARM state. Reason: Threshold crossed: 1 out of 1 datapoints was greater than the threshold (500ms).',
    html: '',
    attachments: [],
    flags: { seen: false, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 4000,
    date: days(3),
    receivedAt: days(3),
  },
  {
    _id: 'msg-13',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg13@example.com>',
    from: { name: 'Lisa Wang', address: 'lisa.wang@partner.co' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Partnership proposal — content collaboration',
    text: 'Hi there! I\'m reaching out about a potential content collaboration between our teams. We\'ve been following your product and think there\'s a great opportunity for a joint webinar or case study. I\'ve attached a brief proposal with some ideas. Would love to chat!',
    html: '',
    attachments: [
      { filename: 'partnership-proposal.pdf', contentType: 'application/pdf', size: 520000, s3Key: 'att-13' },
      { filename: 'case-study-draft.docx', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: 180000, s3Key: 'att-14' },
    ],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 712000,
    date: days(4),
    receivedAt: days(4),
  },
  {
    _id: 'msg-14',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg14@example.com>',
    from: { name: 'Figma', address: 'noreply@figma.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Sarah Chen invited you to "Inbox App Redesign"',
    text: 'Sarah Chen has invited you to collaborate on the Figma file "Inbox App Redesign". Click the link below to open the file and start collaborating.',
    html: '',
    attachments: [],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 8000,
    date: days(5),
    receivedAt: days(5),
  },
  {
    _id: 'msg-15',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg15@example.com>',
    from: { name: 'Tom Baker', address: 'tom.baker@photos.studio' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Product photoshoot — final selects',
    text: 'Hey! Here are the final selects from the product photoshoot. I\'ve included the hi-res versions and the edited batch. Let me know if you need any retouching or color adjustments.',
    html: '',
    attachments: [
      { filename: 'hero-shot.jpg', contentType: 'image/jpeg', size: 4800000, s3Key: 'att-15' },
      { filename: 'product-angle-1.jpg', contentType: 'image/jpeg', size: 3200000, s3Key: 'att-16' },
      { filename: 'product-angle-2.jpg', contentType: 'image/jpeg', size: 3500000, s3Key: 'att-17' },
      { filename: 'lifestyle-shot.jpg', contentType: 'image/jpeg', size: 5100000, s3Key: 'att-18' },
    ],
    flags: { seen: true, starred: true, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 16700000,
    date: days(6),
    receivedAt: days(6),
  },
  {
    _id: 'msg-16',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg16@example.com>',
    from: { name: 'Slack', address: 'feedback@slack.com' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'New message from #engineering in OxyHQ workspace',
    text: 'Marcus Rivera posted in #engineering: "Just deployed the fix for the token refresh issue. Monitoring dashboards look clean. Going to keep an eye on it for the next hour."',
    html: '',
    attachments: [],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 5000,
    date: days(7),
    receivedAt: days(7),
  },
  {
    _id: 'msg-17',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg17@example.com>',
    from: { name: 'Mike Chen', address: 'mike@recording.studio' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Podcast episode recording — rough cut',
    text: 'Here\'s the rough cut of last week\'s podcast episode. I\'ve done basic noise reduction and leveling. Let me know if you want me to adjust the intro music timing or add the sponsor reads.',
    html: '',
    attachments: [
      { filename: 'episode-42-rough.mp3', contentType: 'audio/mpeg', size: 48000000, s3Key: 'att-19' },
      { filename: 'show-notes.docx', contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: 15000, s3Key: 'att-20' },
    ],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 48100000,
    date: days(8),
    receivedAt: days(8),
  },
  {
    _id: 'msg-18',
    userId: 'user-1',
    mailboxId: 'mb-inbox',
    messageId: '<msg18@example.com>',
    from: { name: 'Jordan Lee', address: 'jordan@marketing.team' },
    to: [{ name: 'Me', address: 'me@oxy.so' }],
    subject: 'Launch video — first draft for review',
    text: 'Team, the launch video first draft is ready! It\'s a 2-minute product overview with the new feature highlights. I also attached the presentation we\'ll use at the launch event. Feedback by EOD Thursday please.',
    html: '',
    attachments: [
      { filename: 'launch-video-v1.mp4', contentType: 'video/mp4', size: 85000000, s3Key: 'att-21' },
      { filename: 'launch-deck.pptx', contentType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', size: 12000000, s3Key: 'att-22' },
    ],
    flags: { seen: true, starred: false, answered: false, forwarded: false, draft: false },
    labels: [],
    size: 97200000,
    date: days(10),
    receivedAt: days(10),
  },
];
