name: oxy-proxy
region: nyc
services:
  - name: web
    github:
      repo: OxyHQ/OxyHQServices
      branch: main
      deploy_on_push: true
    source_dir: packages/oxy-proxy
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
