name: oxyhq-auth
region: nyc

services:
  - name: auth
    # Source configuration
    github:
      repo: oxyhq/services  # Replace with your GitHub repo
      branch: main
      deploy_on_push: true

    # Build configuration for monorepo
    source_dir: /
    build_command: npm run auth:build
    run_command: npm run auth:start

    # Environment
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs

    # HTTP configuration
    http_port: 3000

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables (add your secrets here)
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      # Add more environment variables as needed:
      # - key: DATABASE_URL
      #   value: ${db.DATABASE_URL}
      #   type: SECRET
      # - key: JWT_SECRET
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: NEXTAUTH_URL
      #   value: ${APP_URL}
      # - key: NEXTAUTH_SECRET
      #   scope: RUN_TIME
      #   type: SECRET

# Optional: Add database if needed
# databases:
#   - name: auth-db
#     engine: PG
#     version: "15"
#     production: true
#     cluster_name: oxyhq-cluster

# Optional: Add Redis if needed
# databases:
#   - name: auth-redis
#     engine: REDIS
#     version: "7"
