name: Bug Report
description: Report something that isn't working
labels: ["type: bug"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - "@oxyhq/core"
        - "@oxyhq/auth"
        - "@oxyhq/services"
        - "@oxyhq/api"
        - "accounts app"
        - "auth app"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - iOS
        - Android
        - Web
        - Node.js / Server
        - All
