/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUsageRouteImport } from './routes/_layout/usage'
import { Route as LayoutPlaygroundRouteImport } from './routes/_layout/playground'
import { Route as LayoutModelsRouteImport } from './routes/_layout/models'
import { Route as LayoutExamplesRouteImport } from './routes/_layout/examples'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutBillingRouteImport } from './routes/_layout/billing'
import { Route as LayoutDocumentationIndexRouteImport } from './routes/_layout/documentation/index'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutSettingsWorkspaceRouteImport } from './routes/_layout/settings/workspace'
import { Route as LayoutDocumentationSdksRouteImport } from './routes/_layout/documentation/sdks'
import { Route as LayoutDocumentationQuickstartRouteImport } from './routes/_layout/documentation/quickstart'
import { Route as LayoutDocumentationModelsRouteImport } from './routes/_layout/documentation/models'
import { Route as LayoutDocumentationChatCompletionsRouteImport } from './routes/_layout/documentation/chat-completions'
import { Route as LayoutDocumentationAuthenticationRouteImport } from './routes/_layout/documentation/authentication'
import { Route as LayoutAppsAppIdIndexRouteImport } from './routes/_layout/apps/$appId/index'
import { Route as LayoutAppsAppIdUsageRouteImport } from './routes/_layout/apps/$appId/usage'
import { Route as LayoutAppsAppIdSettingsRouteImport } from './routes/_layout/apps/$appId/settings'
import { Route as LayoutAppsAppIdKeysKeyIdRouteImport } from './routes/_layout/apps/$appId/keys/$keyId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsageRoute = LayoutUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundRoute = LayoutPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsRoute = LayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamplesRoute = LayoutExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentationIndexRoute =
  LayoutDocumentationIndexRouteImport.update({
    id: '/documentation/',
    path: '/documentation/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAppsIndexRoute = LayoutAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsWorkspaceRoute = LayoutSettingsWorkspaceRouteImport.update({
  id: '/settings/workspace',
  path: '/settings/workspace',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentationSdksRoute = LayoutDocumentationSdksRouteImport.update({
  id: '/documentation/sdks',
  path: '/documentation/sdks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentationQuickstartRoute =
  LayoutDocumentationQuickstartRouteImport.update({
    id: '/documentation/quickstart',
    path: '/documentation/quickstart',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDocumentationModelsRoute =
  LayoutDocumentationModelsRouteImport.update({
    id: '/documentation/models',
    path: '/documentation/models',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDocumentationChatCompletionsRoute =
  LayoutDocumentationChatCompletionsRouteImport.update({
    id: '/documentation/chat-completions',
    path: '/documentation/chat-completions',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDocumentationAuthenticationRoute =
  LayoutDocumentationAuthenticationRouteImport.update({
    id: '/documentation/authentication',
    path: '/documentation/authentication',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAppsAppIdIndexRoute = LayoutAppsAppIdIndexRouteImport.update({
  id: '/apps/$appId/',
  path: '/apps/$appId/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsAppIdUsageRoute = LayoutAppsAppIdUsageRouteImport.update({
  id: '/apps/$appId/usage',
  path: '/apps/$appId/usage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsAppIdSettingsRoute = LayoutAppsAppIdSettingsRouteImport.update({
  id: '/apps/$appId/settings',
  path: '/apps/$appId/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsAppIdKeysKeyIdRoute =
  LayoutAppsAppIdKeysKeyIdRouteImport.update({
    id: '/apps/$appId/keys/$keyId',
    path: '/apps/$appId/keys/$keyId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/examples': typeof LayoutExamplesRoute
  '/models': typeof LayoutModelsRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/usage': typeof LayoutUsageRoute
  '/documentation/authentication': typeof LayoutDocumentationAuthenticationRoute
  '/documentation/chat-completions': typeof LayoutDocumentationChatCompletionsRoute
  '/documentation/models': typeof LayoutDocumentationModelsRoute
  '/documentation/quickstart': typeof LayoutDocumentationQuickstartRoute
  '/documentation/sdks': typeof LayoutDocumentationSdksRoute
  '/settings/workspace': typeof LayoutSettingsWorkspaceRoute
  '/apps/': typeof LayoutAppsIndexRoute
  '/documentation/': typeof LayoutDocumentationIndexRoute
  '/apps/$appId/settings': typeof LayoutAppsAppIdSettingsRoute
  '/apps/$appId/usage': typeof LayoutAppsAppIdUsageRoute
  '/apps/$appId/': typeof LayoutAppsAppIdIndexRoute
  '/apps/$appId/keys/$keyId': typeof LayoutAppsAppIdKeysKeyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof LayoutBillingRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/examples': typeof LayoutExamplesRoute
  '/models': typeof LayoutModelsRoute
  '/playground': typeof LayoutPlaygroundRoute
  '/usage': typeof LayoutUsageRoute
  '/documentation/authentication': typeof LayoutDocumentationAuthenticationRoute
  '/documentation/chat-completions': typeof LayoutDocumentationChatCompletionsRoute
  '/documentation/models': typeof LayoutDocumentationModelsRoute
  '/documentation/quickstart': typeof LayoutDocumentationQuickstartRoute
  '/documentation/sdks': typeof LayoutDocumentationSdksRoute
  '/settings/workspace': typeof LayoutSettingsWorkspaceRoute
  '/apps': typeof LayoutAppsIndexRoute
  '/documentation': typeof LayoutDocumentationIndexRoute
  '/apps/$appId/settings': typeof LayoutAppsAppIdSettingsRoute
  '/apps/$appId/usage': typeof LayoutAppsAppIdUsageRoute
  '/apps/$appId': typeof LayoutAppsAppIdIndexRoute
  '/apps/$appId/keys/$keyId': typeof LayoutAppsAppIdKeysKeyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/examples': typeof LayoutExamplesRoute
  '/_layout/models': typeof LayoutModelsRoute
  '/_layout/playground': typeof LayoutPlaygroundRoute
  '/_layout/usage': typeof LayoutUsageRoute
  '/_layout/documentation/authentication': typeof LayoutDocumentationAuthenticationRoute
  '/_layout/documentation/chat-completions': typeof LayoutDocumentationChatCompletionsRoute
  '/_layout/documentation/models': typeof LayoutDocumentationModelsRoute
  '/_layout/documentation/quickstart': typeof LayoutDocumentationQuickstartRoute
  '/_layout/documentation/sdks': typeof LayoutDocumentationSdksRoute
  '/_layout/settings/workspace': typeof LayoutSettingsWorkspaceRoute
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/documentation/': typeof LayoutDocumentationIndexRoute
  '/_layout/apps/$appId/settings': typeof LayoutAppsAppIdSettingsRoute
  '/_layout/apps/$appId/usage': typeof LayoutAppsAppIdUsageRoute
  '/_layout/apps/$appId/': typeof LayoutAppsAppIdIndexRoute
  '/_layout/apps/$appId/keys/$keyId': typeof LayoutAppsAppIdKeysKeyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/examples'
    | '/models'
    | '/playground'
    | '/usage'
    | '/documentation/authentication'
    | '/documentation/chat-completions'
    | '/documentation/models'
    | '/documentation/quickstart'
    | '/documentation/sdks'
    | '/settings/workspace'
    | '/apps/'
    | '/documentation/'
    | '/apps/$appId/settings'
    | '/apps/$appId/usage'
    | '/apps/$appId/'
    | '/apps/$appId/keys/$keyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/examples'
    | '/models'
    | '/playground'
    | '/usage'
    | '/documentation/authentication'
    | '/documentation/chat-completions'
    | '/documentation/models'
    | '/documentation/quickstart'
    | '/documentation/sdks'
    | '/settings/workspace'
    | '/apps'
    | '/documentation'
    | '/apps/$appId/settings'
    | '/apps/$appId/usage'
    | '/apps/$appId'
    | '/apps/$appId/keys/$keyId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/billing'
    | '/_layout/dashboard'
    | '/_layout/examples'
    | '/_layout/models'
    | '/_layout/playground'
    | '/_layout/usage'
    | '/_layout/documentation/authentication'
    | '/_layout/documentation/chat-completions'
    | '/_layout/documentation/models'
    | '/_layout/documentation/quickstart'
    | '/_layout/documentation/sdks'
    | '/_layout/settings/workspace'
    | '/_layout/apps/'
    | '/_layout/documentation/'
    | '/_layout/apps/$appId/settings'
    | '/_layout/apps/$appId/usage'
    | '/_layout/apps/$appId/'
    | '/_layout/apps/$appId/keys/$keyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/usage': {
      id: '/_layout/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof LayoutUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground': {
      id: '/_layout/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof LayoutPlaygroundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models': {
      id: '/_layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof LayoutModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/examples': {
      id: '/_layout/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof LayoutExamplesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documentation/': {
      id: '/_layout/documentation/'
      path: '/documentation'
      fullPath: '/documentation/'
      preLoaderRoute: typeof LayoutDocumentationIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/': {
      id: '/_layout/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/workspace': {
      id: '/_layout/settings/workspace'
      path: '/settings/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof LayoutSettingsWorkspaceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documentation/sdks': {
      id: '/_layout/documentation/sdks'
      path: '/documentation/sdks'
      fullPath: '/documentation/sdks'
      preLoaderRoute: typeof LayoutDocumentationSdksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documentation/quickstart': {
      id: '/_layout/documentation/quickstart'
      path: '/documentation/quickstart'
      fullPath: '/documentation/quickstart'
      preLoaderRoute: typeof LayoutDocumentationQuickstartRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documentation/models': {
      id: '/_layout/documentation/models'
      path: '/documentation/models'
      fullPath: '/documentation/models'
      preLoaderRoute: typeof LayoutDocumentationModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documentation/chat-completions': {
      id: '/_layout/documentation/chat-completions'
      path: '/documentation/chat-completions'
      fullPath: '/documentation/chat-completions'
      preLoaderRoute: typeof LayoutDocumentationChatCompletionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documentation/authentication': {
      id: '/_layout/documentation/authentication'
      path: '/documentation/authentication'
      fullPath: '/documentation/authentication'
      preLoaderRoute: typeof LayoutDocumentationAuthenticationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/$appId/': {
      id: '/_layout/apps/$appId/'
      path: '/apps/$appId'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof LayoutAppsAppIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/$appId/usage': {
      id: '/_layout/apps/$appId/usage'
      path: '/apps/$appId/usage'
      fullPath: '/apps/$appId/usage'
      preLoaderRoute: typeof LayoutAppsAppIdUsageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/$appId/settings': {
      id: '/_layout/apps/$appId/settings'
      path: '/apps/$appId/settings'
      fullPath: '/apps/$appId/settings'
      preLoaderRoute: typeof LayoutAppsAppIdSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/$appId/keys/$keyId': {
      id: '/_layout/apps/$appId/keys/$keyId'
      path: '/apps/$appId/keys/$keyId'
      fullPath: '/apps/$appId/keys/$keyId'
      preLoaderRoute: typeof LayoutAppsAppIdKeysKeyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutExamplesRoute: typeof LayoutExamplesRoute
  LayoutModelsRoute: typeof LayoutModelsRoute
  LayoutPlaygroundRoute: typeof LayoutPlaygroundRoute
  LayoutUsageRoute: typeof LayoutUsageRoute
  LayoutDocumentationAuthenticationRoute: typeof LayoutDocumentationAuthenticationRoute
  LayoutDocumentationChatCompletionsRoute: typeof LayoutDocumentationChatCompletionsRoute
  LayoutDocumentationModelsRoute: typeof LayoutDocumentationModelsRoute
  LayoutDocumentationQuickstartRoute: typeof LayoutDocumentationQuickstartRoute
  LayoutDocumentationSdksRoute: typeof LayoutDocumentationSdksRoute
  LayoutSettingsWorkspaceRoute: typeof LayoutSettingsWorkspaceRoute
  LayoutAppsIndexRoute: typeof LayoutAppsIndexRoute
  LayoutDocumentationIndexRoute: typeof LayoutDocumentationIndexRoute
  LayoutAppsAppIdSettingsRoute: typeof LayoutAppsAppIdSettingsRoute
  LayoutAppsAppIdUsageRoute: typeof LayoutAppsAppIdUsageRoute
  LayoutAppsAppIdIndexRoute: typeof LayoutAppsAppIdIndexRoute
  LayoutAppsAppIdKeysKeyIdRoute: typeof LayoutAppsAppIdKeysKeyIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutExamplesRoute: LayoutExamplesRoute,
  LayoutModelsRoute: LayoutModelsRoute,
  LayoutPlaygroundRoute: LayoutPlaygroundRoute,
  LayoutUsageRoute: LayoutUsageRoute,
  LayoutDocumentationAuthenticationRoute:
    LayoutDocumentationAuthenticationRoute,
  LayoutDocumentationChatCompletionsRoute:
    LayoutDocumentationChatCompletionsRoute,
  LayoutDocumentationModelsRoute: LayoutDocumentationModelsRoute,
  LayoutDocumentationQuickstartRoute: LayoutDocumentationQuickstartRoute,
  LayoutDocumentationSdksRoute: LayoutDocumentationSdksRoute,
  LayoutSettingsWorkspaceRoute: LayoutSettingsWorkspaceRoute,
  LayoutAppsIndexRoute: LayoutAppsIndexRoute,
  LayoutDocumentationIndexRoute: LayoutDocumentationIndexRoute,
  LayoutAppsAppIdSettingsRoute: LayoutAppsAppIdSettingsRoute,
  LayoutAppsAppIdUsageRoute: LayoutAppsAppIdUsageRoute,
  LayoutAppsAppIdIndexRoute: LayoutAppsAppIdIndexRoute,
  LayoutAppsAppIdKeysKeyIdRoute: LayoutAppsAppIdKeysKeyIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
